tap "elastic/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "railwaycat/emacsmacport"
tap "rbenv/tap"
brew "glib"
brew "harfbuzz"
brew "openjdk"
brew "allure"
brew "pycparser"
brew "cffi"
brew "cryptography"
brew "python@3.12"
brew "ansible"
brew "jpeg-xl"
brew "asdf"
brew "python@3.11"
brew "awscli"
brew "azure-cli"
brew "carthage"
brew "ctop"
brew "docutils"
brew "gh"
brew "ghostscript"
brew "git"
brew "glow"
brew "libidn2"
brew "unbound", restart_service: :changed
brew "gnutls"
brew "gnupg"
brew "librsvg"
brew "graphviz"
brew "protobuf"
brew "grpc"
brew "shared-mime-info"
brew "libheif"
brew "libraw"
brew "imagemagick"
brew "memcached", restart_service: :changed
brew "mysql@5.7", restart_service: :changed, link: true
brew "nginx", restart_service: :changed
brew "postgresql@14", restart_service: :changed
brew "python@3.10"
brew "python@3.9"
brew "rbspy"
brew "redis", restart_service: :changed
brew "ripgrep"
brew "universal-ctags"
brew "rbenv/tap/openssl@1.0"
cask "chromedriver"
cask "emacs-mac-spacemacs-icon"
